export const SETGAMEGROUP = 'SETGAMEGROUP';
export const CLEANGAMEGROUP = 'CLEANGAMEGROUP';
export const SETSELECTEDGAME = 'SETSELECTEDGAME';
export const CLEANSELECTEDGAME = 'CLEANSELECTEDGAME';
export const SETGAMESTATE = 'SETGAMESTATE';
export const CLEANGAMESTATE = 'CLEANSELECTEDGAME';
